// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };


type PickContentRelationshipFieldData<
	TRelationship extends prismic.CustomTypeModelFetchCustomTypeLevel1 | prismic.CustomTypeModelFetchCustomTypeLevel2 | prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2,
	TData extends Record<string, prismic.AnyRegularField | prismic.GroupField | prismic.NestedGroupField | prismic.SliceZone>,
	TLang extends string
> = |
	// Content relationship fields
	{
		[TSubRelationship in Extract<
			TRelationship["fields"][number], prismic.CustomTypeModelFetchContentRelationshipLevel1
		> as TSubRelationship["id"]]:
			ContentRelationshipFieldWithData<TSubRelationship["customtypes"], TLang>;
	} &
	// Group
	{
		[TGroup in Extract<
			TRelationship["fields"][number], prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2
		> as TGroup["id"]]:
			TData[TGroup["id"]] extends prismic.GroupField<infer TGroupData>
				? prismic.GroupField<PickContentRelationshipFieldData<TGroup, TGroupData, TLang>>
				: never
	} &
	// Other fields
	{
		[TFieldKey in Extract<TRelationship["fields"][number], string>]:
			TFieldKey extends keyof TData ? TData[TFieldKey] : never;
	};

type ContentRelationshipFieldWithData<
	TCustomType extends readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[] | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
	TLang extends string = string
> = {
	[ID in Exclude<TCustomType[number], string>["id"]]:
		prismic.ContentRelationshipField<
			ID,
			TLang,
			PickContentRelationshipFieldData<
				Extract<TCustomType[number], { id: ID }>,
				Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
				TLang
			>
		>
}[Exclude<TCustomType[number], string>["id"]];

type ContactPageDocumentDataSlicesSlice = ContactFormSlice

/**
 * Content for Contact Page documents
 */
interface ContactPageDocumentData {
	/**
	 * Title field in *Contact Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact_page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * Description field in *Contact Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact_page.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
	
	/**
	 * Slice Zone field in *Contact Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact_page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<ContactPageDocumentDataSlicesSlice>;/**
	 * Meta Title field in *Contact Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: contact_page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;
	
	/**
	 * Meta Description field in *Contact Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: contact_page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;
	
	/**
	 * Meta Image field in *Contact Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact_page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Contact Page document from Prismic
 *
 * - **API ID**: `contact_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactPageDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<ContactPageDocumentData>, "contact_page", Lang>;

type FragranceDocumentDataSlicesSlice = never

/**
 * Content for Fragrance documents
 */
interface FragranceDocumentData {
	/**
	 * Title field in *Fragrance*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fragrance.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * Bottle Image field in *Fragrance*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fragrance.bottle_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	bottle_image: prismic.ImageField<never>;
	
	/**
	 * Feature Image field in *Fragrance*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fragrance.feature_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	feature_image: prismic.ImageField<never>;
	
	/**
	 * Description field in *Fragrance*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fragrance.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
	
	/**
	 * Price field in *Fragrance*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: (In cents)
	 * - **API ID Path**: fragrance.price
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/number
	 */
	price: prismic.NumberField;
	
	/**
	 * Scent Profile field in *Fragrance*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: spicy
	 * - **API ID Path**: fragrance.scent_profile
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	scent_profile: prismic.SelectField<"spicy" | "woody" | "fresh", "filled">;
	
	/**
	 * Mood field in *Fragrance*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: bold
	 * - **API ID Path**: fragrance.mood
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	mood: prismic.SelectField<"bold" | "grounded" | "refreshing", "filled">;
	
	/**
	 * Slice Zone field in *Fragrance*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fragrance.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<FragranceDocumentDataSlicesSlice>;/**
	 * Meta Image field in *Fragrance*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fragrance.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Fragrance document from Prismic
 *
 * - **API ID**: `fragrance`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FragranceDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<FragranceDocumentData>, "fragrance", Lang>;

type HomepageDocumentDataSlicesSlice = VideoSlice | CallToActionSlice | FragranceListSlice | ProductFeatureSlice | ScrollTextSlice | HeroSlice

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
	/**
	 * Slice Zone field in *Homepage*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>;/**
	 * Meta Title field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: homepage.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;
	
	/**
	 * Meta Description field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: homepage.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;
	
	/**
	 * Meta Image field in *Homepage*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<HomepageDocumentData>, "homepage", Lang>;

type NotFoundPageDocumentDataSlicesSlice = never

/**
 * Content for Not Found Page documents
 */
interface NotFoundPageDocumentData {
	/**
	 * Heading field in *Not Found Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: not_found_page.heading
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	heading: prismic.RichTextField;
	
	/**
	 * Body field in *Not Found Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: not_found_page.body
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	body: prismic.RichTextField;
	
	/**
	 * Button field in *Not Found Page*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: not_found_page.button
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Image field in *Not Found Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: not_found_page.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * Slice Zone field in *Not Found Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: not_found_page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<NotFoundPageDocumentDataSlicesSlice>;/**
	 * Meta Title field in *Not Found Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: not_found_page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;
	
	/**
	 * Meta Description field in *Not Found Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: not_found_page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;
	
	/**
	 * Meta Image field in *Not Found Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: not_found_page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Not Found Page document from Prismic
 *
 * - **API ID**: `not_found_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NotFoundPageDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<NotFoundPageDocumentData>, "not_found_page", Lang>;

/**
 * Item in *Quiz → Questions*
 */
export interface QuizDocumentDataQuestionsItem {
	/**
	 * Question Text field in *Quiz → Questions*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: quiz.questions[].question_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	question_text: prismic.KeyTextField;
	
	/**
	 * Image Terra field in *Quiz → Questions*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: quiz.questions[].image_terra
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image_terra: prismic.ImageField<never>;
	
	/**
	 * Answer Terra field in *Quiz → Questions*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: quiz.questions[].answer_terra
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	answer_terra: prismic.KeyTextField;
	
	/**
	 * Image Ignis field in *Quiz → Questions*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: quiz.questions[].image_ignis
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image_ignis: prismic.ImageField<never>;
	
	/**
	 * Answer Ignis field in *Quiz → Questions*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: quiz.questions[].answer_ignis
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	answer_ignis: prismic.KeyTextField;
	
	/**
	 * Image Aqua field in *Quiz → Questions*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: quiz.questions[].image_aqua
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image_aqua: prismic.ImageField<never>;
	
	/**
	 * Answer Aqua field in *Quiz → Questions*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: quiz.questions[].answer_aqua
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	answer_aqua: prismic.KeyTextField;
}

type QuizDocumentDataSlicesSlice = never

/**
 * Content for Quiz documents
 */
interface QuizDocumentData {
	/**
	 * Eyebrow field in *Quiz*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: quiz.eyebrow
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	eyebrow: prismic.KeyTextField;
	
	/**
	 * Title field in *Quiz*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: quiz.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * Body field in *Quiz*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: quiz.body
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	body: prismic.RichTextField;
	
	/**
	 * Start Button Text field in *Quiz*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: quiz.start_button_text
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	start_button_text: prismic.KeyTextField;
	
	/**
	 * Questions field in *Quiz*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: quiz.questions[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	questions: prismic.GroupField<Simplify<QuizDocumentDataQuestionsItem>>;
	
	/**
	 * Slice Zone field in *Quiz*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: quiz.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<QuizDocumentDataSlicesSlice>;/**
	 * Meta Title field in *Quiz*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: quiz.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;
	
	/**
	 * Meta Description field in *Quiz*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: quiz.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;
	
	/**
	 * Meta Image field in *Quiz*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: quiz.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Quiz document from Prismic
 *
 * - **API ID**: `quiz`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type QuizDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<QuizDocumentData>, "quiz", Lang>;

/**
 * Item in *Settings → Contact Form Settings*
 */
export interface SettingsDocumentDataContactFormSettingsItem {
	/**
	 * Recipient Email field in *Settings → Contact Form Settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.contact_form_settings[].recipient_email
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	recipient_email: prismic.KeyTextField;
	
	/**
	 * Email Subject Template field in *Settings → Contact Form Settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.contact_form_settings[].email_subject_template
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	email_subject_template: prismic.KeyTextField;
	
	/**
	 * Confirmation Email Subject field in *Settings → Contact Form Settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.contact_form_settings[].confirmation_email_subject
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	confirmation_email_subject: prismic.KeyTextField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
	/**
	 * Site Title field in *Settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.site_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	site_title: prismic.KeyTextField;
	
	/**
	 * Meta Description field in *Settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.meta_description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;
	
	/**
	 * Fallback OG Image field in *Settings*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.fallback_og_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	fallback_og_image: prismic.ImageField<never>;
	
	/**
	 * Navigation Link field in *Settings*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.navigation_link
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	navigation_link: prismic.Repeatable<prismic.LinkField<string, string, unknown, prismic.FieldState, never>>;
	
	/**
	 * Contact Form Settings field in *Settings*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.contact_form_settings[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	contact_form_settings: prismic.GroupField<Simplify<SettingsDocumentDataContactFormSettingsItem>>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<SettingsDocumentData>, "settings", Lang>;

/**
 * Content for Translations documents
 */
interface TranslationsDocumentData {
	/**
	 * Add to Bag field in *Translations*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: translations.add_to_bag
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	add_to_bag: prismic.KeyTextField;
	
	/**
	 * You may also like field in *Translations*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: translations.you_may_also_like
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	you_may_also_like: prismic.KeyTextField;
	
	/**
	 * Features field in *Translations*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: translations.features
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	features: prismic.KeyTextField;
	
	/**
	 * Shop field in *Translations*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: translations.shop
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	shop: prismic.KeyTextField;
	
	/**
	 * About field in *Translations*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: translations.about
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	about: prismic.KeyTextField;
	
	/**
	 * Social field in *Translations*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: translations.social
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	social: prismic.KeyTextField;
	
	/**
	 * Terms and Conditions field in *Translations*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: translations.terms_and_conditions
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	terms_and_conditions: prismic.KeyTextField;
	
	/**
	 * Privacy Policy field in *Translations*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: translations.privacy_policy
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	privacy_policy: prismic.KeyTextField;
	
	/**
	 * Quiz: Step field in *Translations*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: translations.quiz_step
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	quiz_step: prismic.KeyTextField;
	
	/**
	 * Quiz: Back Button field in *Translations*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: translations.quiz_back_button
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	quiz_back_button: prismic.KeyTextField;
	
	/**
	 * Quiz: Next Button field in *Translations*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: translations.quiz_next_button
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	quiz_next_button: prismic.KeyTextField;
	
	/**
	 * Quiz: Results Eyebrow field in *Translations*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: translations.quiz_results_eyebrow
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	quiz_results_eyebrow: prismic.KeyTextField;
	
	/**
	 * Quiz: Results Title field in *Translations*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: translations.quiz_results_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	quiz_results_title: prismic.KeyTextField;
	
	/**
	 * Quiz: Results Body field in *Translations*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: translations.quiz_results_body
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	quiz_results_body: prismic.KeyTextField;
	
	/**
	 * Quiz: Results Retake Button field in *Translations*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: translations.quiz_results_retake_button
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	quiz_results_retake_button: prismic.KeyTextField;
	
	/**
	 * Search Modal: Input Placeholder field in *Translations*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: translations.search_modal_input_placeholder
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	search_modal_input_placeholder: prismic.KeyTextField;
	
	/**
	 * Search Modal: Status Loading field in *Translations*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: translations.search_modal_status_loading
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	search_modal_status_loading: prismic.KeyTextField;
	
	/**
	 * Search Modal: No Results Found field in *Translations*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: translations.search_modal_no_results_found
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	search_modal_no_results_found: prismic.KeyTextField;
}

/**
 * Translations document from Prismic
 *
 * - **API ID**: `translations`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TranslationsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<TranslationsDocumentData>, "translations", Lang>;

export type AllDocumentTypes = ContactPageDocument | FragranceDocument | HomepageDocument | NotFoundPageDocument | QuizDocument | SettingsDocument | TranslationsDocument;

/**
 * Primary content in *CallToAction → Default → Primary*
 */
export interface CallToActionSliceDefaultPrimary {
	/**
	 * Eyebrow field in *CallToAction → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: call_to_action.default.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	eyebrow: prismic.KeyTextField;
	
	/**
	 * Heading field in *CallToAction → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: call_to_action.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	heading: prismic.RichTextField;
	
	/**
	 * Body field in *CallToAction → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: call_to_action.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	body: prismic.RichTextField;
	
	/**
	 * Button field in *CallToAction → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: call_to_action.default.primary.button
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	button: prismic.Repeatable<prismic.LinkField<string, string, unknown, prismic.FieldState, "Primary" | "Secondary">>;
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<"default", Simplify<CallToActionSliceDefaultPrimary>, never>;

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation = CallToActionSliceDefault

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CallToActionSlice = prismic.SharedSlice<"call_to_action", CallToActionSliceVariation>;

/**
 * Primary content in *ContactForm → Contact Form → Primary*
 */
export interface ContactFormSliceDefaultPrimary {
	/**
	 * Name Field Label field in *ContactForm → Contact Form → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact_form.default.primary.name_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	name_label: prismic.KeyTextField;
	
	/**
	 * Name Field Placeholder field in *ContactForm → Contact Form → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact_form.default.primary.name_field_placeholder
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	name_field_placeholder: prismic.KeyTextField;
	
	/**
	 * Email Field Label field in *ContactForm → Contact Form → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact_form.default.primary.email_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	email_label: prismic.KeyTextField;
	
	/**
	 * Email Field Placeholder field in *ContactForm → Contact Form → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact_form.default.primary.email_field_placeholder
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	email_field_placeholder: prismic.KeyTextField;
	
	/**
	 * Message Field Label field in *ContactForm → Contact Form → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact_form.default.primary.message_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	message_label: prismic.KeyTextField;
	
	/**
	 * Message Field Placeholder field in *ContactForm → Contact Form → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact_form.default.primary.message_field_placeholder
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	message_field_placeholder: prismic.KeyTextField;
	
	/**
	 * Submit Button Text field in *ContactForm → Contact Form → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact_form.default.primary.submit_button_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	submit_button_text: prismic.KeyTextField;
	
	/**
	 * Loading Text field in *ContactForm → Contact Form → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact_form.default.primary.loading_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	loading_text: prismic.KeyTextField;
	
	/**
	 * Success Message field in *ContactForm → Contact Form → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact_form.default.primary.success_message
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	success_message: prismic.KeyTextField;
}

/**
 * Contact Form variation for ContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactFormSliceDefault = prismic.SharedSliceVariation<"default", Simplify<ContactFormSliceDefaultPrimary>, never>;

/**
 * Slice variation for *ContactForm*
 */
type ContactFormSliceVariation = ContactFormSliceDefault

/**
 * ContactForm Shared Slice
 *
 * - **API ID**: `contact_form`
 * - **Description**: ContactForm
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactFormSlice = prismic.SharedSlice<"contact_form", ContactFormSliceVariation>;

/**
 * Item in *FragranceList → Default → Primary → Fragrances*
 */
export interface FragranceListSliceDefaultPrimaryFragrancesItem {
	/**
	 * Fragrance field in *FragranceList → Default → Primary → Fragrances*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fragrance_list.default.primary.fragrances[].fragrance
	 * - **Documentation**: https://prismic.io/docs/fields/content-relationship
	 */
	fragrance: prismic.ContentRelationshipField<"fragrance">;
}

/**
 * Primary content in *FragranceList → Default → Primary*
 */
export interface FragranceListSliceDefaultPrimary {
	/**
	 * Eyebrow field in *FragranceList → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fragrance_list.default.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	eyebrow: prismic.KeyTextField;
	
	/**
	 * Heading field in *FragranceList → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fragrance_list.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	heading: prismic.RichTextField;
	
	/**
	 * Body field in *FragranceList → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fragrance_list.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	body: prismic.RichTextField;
	
	/**
	 * Fragrances field in *FragranceList → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fragrance_list.default.primary.fragrances[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	fragrances: prismic.GroupField<Simplify<FragranceListSliceDefaultPrimaryFragrancesItem>>;
	
	/**
	 * Button field in *FragranceList → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fragrance_list.default.primary.button
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	button: prismic.KeyTextField;
	
	/**
	 * Add To Bag field in *FragranceList → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fragrance_list.default.primary.add_to_bag
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	add_to_bag: prismic.KeyTextField;
}

/**
 * Default variation for FragranceList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FragranceListSliceDefault = prismic.SharedSliceVariation<"default", Simplify<FragranceListSliceDefaultPrimary>, never>;

/**
 * Slice variation for *FragranceList*
 */
type FragranceListSliceVariation = FragranceListSliceDefault

/**
 * FragranceList Shared Slice
 *
 * - **API ID**: `fragrance_list`
 * - **Description**: FragranceList
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FragranceListSlice = prismic.SharedSlice<"fragrance_list", FragranceListSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
	/**
	 * Heading field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	heading: prismic.RichTextField;
	
	/**
	 * Body field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	body: prismic.RichTextField;
	
	/**
	 * Button field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.button
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	button: prismic.Repeatable<prismic.LinkField<string, string, unknown, prismic.FieldState, "Primary" | "Secondary">>;
	
	/**
	 * Image field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<"default", Simplify<HeroSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *ProductFeature → Default → Primary*
 */
export interface ProductFeatureSliceDefaultPrimary {
	/**
	 * Heading field in *ProductFeature → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product_feature.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	heading: prismic.RichTextField;
	
	/**
	 * Description field in *ProductFeature → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product_feature.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
	
	/**
	 * Feature Image field in *ProductFeature → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product_feature.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * Fragrance field in *ProductFeature → Default → Primary*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product_feature.default.primary.fragrance
	 * - **Documentation**: https://prismic.io/docs/fields/content-relationship
	 */
	fragrance: prismic.ContentRelationshipField<"fragrance">;
	
	/**
	 * Button field in *ProductFeature → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product_feature.default.primary.button
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	button: prismic.KeyTextField;
}

/**
 * Default variation for ProductFeature Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProductFeatureSliceDefault = prismic.SharedSliceVariation<"default", Simplify<ProductFeatureSliceDefaultPrimary>, never>;

/**
 * Slice variation for *ProductFeature*
 */
type ProductFeatureSliceVariation = ProductFeatureSliceDefault

/**
 * ProductFeature Shared Slice
 *
 * - **API ID**: `product_feature`
 * - **Description**: ProductFeature
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProductFeatureSlice = prismic.SharedSlice<"product_feature", ProductFeatureSliceVariation>;

/**
 * Primary content in *ScrollText → Default → Primary*
 */
export interface ScrollTextSliceDefaultPrimary {
	/**
	 * Eyebrow field in *ScrollText → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: scroll_text.default.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	eyebrow: prismic.KeyTextField;
	
	/**
	 * Text field in *ScrollText → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: scroll_text.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	text: prismic.RichTextField;
}

/**
 * Default variation for ScrollText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ScrollTextSliceDefault = prismic.SharedSliceVariation<"default", Simplify<ScrollTextSliceDefaultPrimary>, never>;

/**
 * Slice variation for *ScrollText*
 */
type ScrollTextSliceVariation = ScrollTextSliceDefault

/**
 * ScrollText Shared Slice
 *
 * - **API ID**: `scroll_text`
 * - **Description**: ScrollText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ScrollTextSlice = prismic.SharedSlice<"scroll_text", ScrollTextSliceVariation>;

/**
 * Primary content in *Video → Default → Primary*
 */
export interface VideoSliceDefaultPrimary {
	/**
	 * YouTube Video ID field in *Video → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: eTEsWseiDdg
	 * - **API ID Path**: video.default.primary.youtube_video_id
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	youtube_video_id: prismic.KeyTextField;
}

/**
 * Default variation for Video Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoSliceDefault = prismic.SharedSliceVariation<"default", Simplify<VideoSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Video*
 */
type VideoSliceVariation = VideoSliceDefault

/**
 * Video Shared Slice
 *
 * - **API ID**: `video`
 * - **Description**: Video
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoSlice = prismic.SharedSlice<"video", VideoSliceVariation>;

declare module "@prismicio/client" {
	interface CreateClient {
		(repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
	}
	
	interface CreateWriteClient {
		(repositoryNameOrEndpoint: string, options: prismic.WriteClientConfig): prismic.WriteClient<AllDocumentTypes>;
	}
	
	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}
	
	namespace Content {
		export type {
			ContactPageDocument,
			ContactPageDocumentData,
			ContactPageDocumentDataSlicesSlice,
			FragranceDocument,
			FragranceDocumentData,
			FragranceDocumentDataSlicesSlice,
			HomepageDocument,
			HomepageDocumentData,
			HomepageDocumentDataSlicesSlice,
			NotFoundPageDocument,
			NotFoundPageDocumentData,
			NotFoundPageDocumentDataSlicesSlice,
			QuizDocument,
			QuizDocumentData,
			QuizDocumentDataQuestionsItem,
			QuizDocumentDataSlicesSlice,
			SettingsDocument,
			SettingsDocumentData,
			SettingsDocumentDataContactFormSettingsItem,
			TranslationsDocument,
			TranslationsDocumentData,
			AllDocumentTypes,
			CallToActionSlice,
			CallToActionSliceDefaultPrimary,
			CallToActionSliceVariation,
			CallToActionSliceDefault,
			ContactFormSlice,
			ContactFormSliceDefaultPrimary,
			ContactFormSliceVariation,
			ContactFormSliceDefault,
			FragranceListSlice,
			FragranceListSliceDefaultPrimaryFragrancesItem,
			FragranceListSliceDefaultPrimary,
			FragranceListSliceVariation,
			FragranceListSliceDefault,
			HeroSlice,
			HeroSliceDefaultPrimary,
			HeroSliceVariation,
			HeroSliceDefault,
			ProductFeatureSlice,
			ProductFeatureSliceDefaultPrimary,
			ProductFeatureSliceVariation,
			ProductFeatureSliceDefault,
			ScrollTextSlice,
			ScrollTextSliceDefaultPrimary,
			ScrollTextSliceVariation,
			ScrollTextSliceDefault,
			VideoSlice,
			VideoSliceDefaultPrimary,
			VideoSliceVariation,
			VideoSliceDefault
		}
	}
}